# Generated by Django 5.0.6 on 2024-07-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_id_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
