def COLOR_MAP = [
    SUCCESS: 'good',
    FAILURE: 'danger'
]

pipeline {
    agent any

    options{
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    stages{
        stage('Checkout & Environment'){
            steps{
                git url: 'https://github.com/rakulvm/GreenSync-IAT.git'
                sh 'python3 --version'
            }
        }
        stage('Docker Build'){
            steps{
                sh 'docker build -t rakul21/django_e2e:latest --no-cache .'
            }
        }
        stage('Docker Hub Login'){
            steps{
                withCredentials([
                    usernamePassword(
                        credentialsId: 'docker-cred', 
                        passwordVariable: 'DOCKERHUB_PASS', 
                        usernameVariable: 'DOCKERHUB_USER')
                    ]) 
                {
                    sh 'echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin'
                }
        }
        }
        stage('Docker Push'){
            steps{
                sh 'docker images'
                sh 'docker images | grep django_e2e'
                sh 'docker push rakul21/django_e2e:latest'
            }
        }
        stage('Run the container'){
            steps{
                sh 'docker-compose up -d'
            }
        }
    }

    post{
        success{
            mail to: 'rakulmanokaran@gmail.com',
                 subject: "Build Success: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: """<html>
                         <p style="color: ${COLOR_MAP['SUCCESS']}">The build was successful.</p>
                         <p>Check the details here: ${env.BUILD_URL}</p>
                         </html>""",
                 mimeType: 'text/html'
        }
        failure{
            mail to: 'rakulmanokaran@gmail.com',
                 subject: "Build Failure: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'",
                 body: """<html>
                         <p style="color: ${COLOR_MAP['FAILURE']}">The build was failure.</p>
                         <p>Check the details here: ${env.BUILD_URL}</p>
                         </html>""",
                 mimeType: 'text/html'
        }
    }
}